import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import TRPCProvider from "./_trpc/TRPCProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider appearance={{
            variables: {
                colorBackground: "#1f222a",
                colorText: '#e4e4e4',
                colorPrimary: '#9164ee',
                colorNeutral: "#ffffff",
            }
        }}>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-background text-primary-text`}
                >
                    <TRPCProvider>
                        {children}
                    </TRPCProvider>
                    <ToastContainer />
                </body>
            </html>
        </ClerkProvider>
    );
}
